#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/configs/local.env"

quote_env() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

if [ -f "$ENV_FILE" ]; then
  exit 0
fi

mkdir -p "$ROOT_DIR/configs"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/ensure-local-env.sh
# Local-only file. Do not commit.

COMPOSE_PROJECT_NAME=hermeswebui

HERMES_JUPYTERHUB_PORT=8000
HERMES_ADMIN_PORT=8001

HERMES_PROJECT_ROOT="$(quote_env "$ROOT_DIR")"
HERMES_HOST_USER_DATA_ROOT="$(quote_env "$ROOT_DIR/.data/users")"
HERMES_HOST_PROVISIONED_SKILLS_ROOT="$(quote_env "$ROOT_DIR/skills")"
HERMES_HOST_POLICY_ROOT="$(quote_env "$ROOT_DIR/configs/policies")"
HERMES_HOST_JUPYTERHUB_DATA_ROOT="$(quote_env "$ROOT_DIR/.data/jupyterhub")"
HERMES_HOST_ADMIN_DATA_ROOT="$(quote_env "$ROOT_DIR/.data/admin")"

HERMES_ADMIN_PASSWORD=local-admin
HERMES_ADMIN_API_TOKEN=local-admin

APP_ENV=local
HERMES_WEBUI_DEFAULT_THEME=light
HERMES_WEBUI_DEFAULT_LANGUAGE=zh
HERMES_WEBUI_ONBOARDING_OPEN=1

JUPYTERHUB_AUTH_MODE=native
JUPYTERHUB_ADMIN_USERS=admin
JUPYTERHUB_ALLOW_ALL=true
JUPYTERHUB_OPEN_SIGNUP=true
JUPYTERHUB_BASE_URL=/
JUPYTERHUB_DEFAULT_URL=/hub/home
JUPYTERHUB_ADMIN_API_TOKEN=local-jupyterhub-admin-token
HERMES_SMOKE_USER=smoke

HERMES_RUNTIME_IMAGE=hermes-runtime:local
DOCKER_NETWORK_NAME=hermes-net

MODEL_PROVIDER=openai-compatible
MODEL_BASE_URL=http://host.docker.internal:3001/v1
MODEL_API_KEY=
MODEL_DEFAULT=local-private-default

JUPYTERHUB_URL=http://127.0.0.1:8000
HERMES_ADMIN_URL=http://127.0.0.1:8001
EOF

echo "Created $ENV_FILE"
